import { NextRequest, NextResponse } from 'next/server';
import { getCurrentUser } from '@/lib/auth';
import getDb from '@/lib/db';

// GET /api/export?videoId=xxx&format=srt|vtt|markdown|json
export async function GET(request: NextRequest) {
  try {
    const user = await getCurrentUser();
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { searchParams } = new URL(request.url);
    const videoId = searchParams.get('videoId');
    const format = searchParams.get('format') || 'srt';

    if (!videoId) return NextResponse.json({ error: 'videoId required' }, { status: 400 });

    const db = getDb();
    const video = db.prepare('SELECT * FROM videos WHERE id = ?').get(videoId) as Record<string, string | number> | undefined;
    if (!video) return NextResponse.json({ error: 'Video not found' }, { status: 404 });

    const transcripts = db.prepare('SELECT * FROM transcripts WHERE video_id = ? ORDER BY start_time').all(videoId) as Array<{ start_time: number; end_time: number; text: string }>;
    const chapters = db.prepare('SELECT * FROM chapters WHERE video_id = ? ORDER BY order_index').all(videoId) as Array<{ title: string; title_en: string; start_time: number; end_time: number; summary: string; summary_en: string }>;
    const materials = db.prepare('SELECT * FROM teaching_materials WHERE video_id = ?').all(videoId) as Array<{ type: string; content: string; content_en: string }>;
    const annotations = db.prepare('SELECT * FROM annotations WHERE video_id = ? ORDER BY timestamp').all(videoId) as Array<{ timestamp: number; label: string; label_en: string; description: string }>;

    const fmt = (s: number) => {
      const h = Math.floor(s / 3600);
      const m = Math.floor((s % 3600) / 60);
      const sec = Math.floor(s % 60);
      const ms = Math.floor((s % 1) * 1000);
      return `${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(sec).padStart(2, '0')},${String(ms).padStart(3, '0')}`;
    };

    const fmtVTT = (s: number) => fmt(s).replace(',', '.');

    // === SRT ===
    if (format === 'srt') {
      const srt = transcripts.map((t, i) =>
        `${i + 1}\n${fmt(t.start_time)} --> ${fmt(t.end_time)}\n${t.text}\n`
      ).join('\n');
      return new NextResponse(srt, {
        headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Content-Disposition': `attachment; filename="${video.title}.srt"` },
      });
    }

    // === VTT ===
    if (format === 'vtt') {
      const vtt = 'WEBVTT\n\n' + transcripts.map((t, i) =>
        `${i + 1}\n${fmtVTT(t.start_time)} --> ${fmtVTT(t.end_time)}\n${t.text}\n`
      ).join('\n');
      return new NextResponse(vtt, {
        headers: { 'Content-Type': 'text/vtt; charset=utf-8', 'Content-Disposition': `attachment; filename="${video.title}.vtt"` },
      });
    }

    // === Markdown teaching material ===
    if (format === 'markdown') {
      const summary = materials.find(m => m.type === 'summary');
      const steps = materials.filter(m => m.type === 'step');

      let md = `# ${video.title}\n\n`;
      md += `**主刀醫師**: ${video.surgeon_name || 'N/A'}  \n`;
      md += `**手術類型**: ${video.surgery_type || 'N/A'}  \n`;
      md += `**難度**: ${video.difficulty}  \n`;
      md += `**時長**: ${Math.floor((video.duration as number) / 60)} 分鐘\n\n`;
      md += `---\n\n`;

      if (summary) {
        md += `## 手術摘要\n\n${summary.content}\n\n`;
        if (summary.content_en) md += `> ${summary.content_en}\n\n`;
      }

      if (chapters.length > 0) {
        md += `## 章節\n\n`;
        chapters.forEach((ch, i) => {
          md += `### ${i + 1}. ${ch.title} (${Math.floor(ch.start_time / 60)}:${String(Math.floor(ch.start_time % 60)).padStart(2, '0')})\n\n`;
          if (ch.summary) md += `${ch.summary}\n\n`;
        });
      }

      if (steps.length > 0) {
        md += `## 手術步驟\n\n`;
        steps.forEach(step => {
          try {
            const data = JSON.parse(step.content);
            md += `**Step ${data.step}: ${data.title}**\n\n${data.description}\n\n`;
          } catch { /* skip */ }
        });
      }

      if (annotations.length > 0) {
        md += `## 關鍵時刻\n\n`;
        annotations.forEach(a => {
          md += `- **[${Math.floor(a.timestamp / 60)}:${String(Math.floor(a.timestamp % 60)).padStart(2, '0')}]** ${a.label}: ${a.description}\n`;
        });
        md += '\n';
      }

      if (transcripts.length > 0) {
        md += `## 完整逐字稿\n\n`;
        transcripts.forEach(t => {
          md += `[${Math.floor(t.start_time / 60)}:${String(Math.floor(t.start_time % 60)).padStart(2, '0')}] ${t.text}\n\n`;
        });
      }

      md += `---\n\n*Generated by SurgAI Platform*\n`;

      return new NextResponse(md, {
        headers: { 'Content-Type': 'text/markdown; charset=utf-8', 'Content-Disposition': `attachment; filename="${video.title}.md"` },
      });
    }

    // === JSON (full data export) ===
    return NextResponse.json({
      video, transcripts, chapters, materials, annotations,
    });

  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Export failed' }, { status: 500 });
  }
}
